version: '3'
services:
    rabbitmq:
        image: 'rabbitmq:3-management'
        container_name: rabbitmq
        ports:
         - 5000:5000
    mysql:
        image: 'mysql'
        environment:
            MYSQL_ROOT_PASSWORD: password
    front-end:
        build: ./front-end
        ports:
            - 5000:5000  
    back-end:
        build: ./back-end
        image: python:3.7-alpine
      
        
       
