version: '3'
services:
    messaging:
        image: 'rabbitmq:3-management'
    mysql:
        image: 'mysql'
        environment:
            MYSQL_ROOT_PASSWORD: password
    front_end:
        build: ./front_end
        ports:
            - 5000:5000  
    back_end:
        image: python:3.7-alpine
        build: ./back_end
        
       
