version: '3'

services:
   db:
     image: mysql
     volumes:
       - db-volume:/var/lib/mysql/data
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: test
       MYSQL_DATABASE: test
       MYSQL_USER: test
       MYSQL_USER: test
       MYSQL_PASSWORD: test
    
volumes:
    db-volume: {}
