---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512M
---
apiVersion: v1
kind: Service
metadata:
  name: db-rw
  labels:
    app: db-rw
spec:
  ports:
  - port: 3306
  selector:
    app: db-rw
  clusterIP: None  
---
apiVersion: v1
kind: Service
metadata:
  name: db-r
  labels:
    app: db-r
spec:
  ports:
  - port: 3306
  selector:
    app: db-r
  clusterIP: None  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-rw
  labels:
    app: db-rw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-rw
  template:
    metadata:
      labels:
        app: db-rw
    spec:
      containers:
      - image: mysql:5.6
        name: db-rw
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: passw
        - name: MYSQL_REPLICA_PASSWORD
          value: "passw"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-primary-storage
          mountPath: /var/lib/mysql/data
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: db-r
  labels:
    app: db-r
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-r
  template:
    metadata:
      labels:
        app: db-r
    spec:
      containers:
      - image: mysql:5.6
        name: db-r
        env:
        - name: MYSQL_REPLICA_PASSWORD
          value: "passw"
        ports:
        - containerPort: 3306
